### ISSUE TITLE
Work with OptionSets

### ISSUE THREAD

**Issue by zaha** [RafaelCavazza/Xrm.Crm.WebApi#14]
Hi @RafaelCavazza,

I just found your library and am liking the API. I'm trying to set an option set value for a lead and couldn't find any OptionSet class or example in the UnitTests. How do I set an optionset value?

Cheers
Michael

**Comment by RafaelCavazza** [comment]
Hi Michael, 

Sorry for the long delayed. 
The API uses the numeric value to set and get the optionset values.

You can simple:  
entity['my_optionset'] = 1;

I culdn't keep up with the project due to the lack of free time, but I'm back to working on it again!
