### ISSUE TITLE
RetrieveMultiple Filter is set to FetchXml

### ISSUE THREAD

**Issue by zaha** [RafaelCavazza/Xrm.Crm.WebApi#15]
There is a bug in the `RetrieveOptions`:

```
if (!string.IsNullOrWhiteSpace(Filter))
    query["$filter"] = FetchXml;
```

It's using the `FetchXml` parameter instead of `Filter`.

**Comment by RafaelCavazza** [comment]
Thanks! 
I'll gather more changes and generate a new nuget version in the coming days.

**Comment by zaha** [comment]
Hi @RafaelCavazza,

that's great to hear. Any news on the new version? :)

Cheers
Michael
