### ISSUE TITLE
LICENSE for NuGet packages

### ISSUE THREAD

**Issue by ariel11** [RafaelCavazza/Xrm.Crm.WebApi#23]
Hi,

Do you intend for these NuGet packages to also be under [the MIT license](https://github.com/RafaelCavazza/Xrm.Crm.WebApi/blob/master/LICENSE) - https://www.nuget.org/packages/Xrm.Crm.WebApi/?

Thanks,
Ariel

**Comment by RafaelCavazza** [comment]
Hi @ariel11 !
Yes I do! Fell free to use as you like.
